# Generated by Django 5.0.2 on 2024-04-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_map_urlsource2_alter_map_urlsource3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.TextField(default='una ubicacion en el mapa'),
        ),
        migrations.AlterField(
            model_name='map',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=100, max_digits=9),
        ),
        migrations.AlterField(
            model_name='map',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=100, max_digits=9),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(default='una ubicacion', max_length=50),
        ),
        migrations.AlterField(
            model_name='map',
            name='zoom',
            field=models.IntegerField(default=100),
        ),
    ]
